"""Pydantic models for API and workflow contracts."""

from app.schemas.auth import (
    AuthLoginRequest,
    AuthRegisterRequest,
    AuthTokenResponse,
    AuthUserResponse,
)
from app.schemas.capabilities import CapabilityMapResponse
from app.schemas.journal import (
    ClarificationResolveRequest,
    ClarificationTaskListResponse,
    ClarificationTaskResponse,
    DerivedStoreCleanupResponse,
    JournalDeleteResponse,
    JournalEntryCreateRequest,
    JournalEntryListResponse,
    JournalEntryResponse,
    JournalIngestResponse,
    LocalDataWipeResponse,
    UserDataDeleteResponse,
    MemorySettingsResponse,
    MemoryDebugResponse,
    GraphNodeResponse,
    GraphObservationResponse,
    GraphRelationshipResponse,
    ProjectionJobListResponse,
    ProjectionJobResponse,
    ProjectionRunResponse,
    WeaviateArtifactResponse,
)
from app.schemas.review import ReviewFindingResponse, ReviewStatResponse, WeeklyReviewResponse
from app.schemas.reflection import ReflectionRequest, ReflectionResponse

SCHEMA_MODELS = [
    ReflectionRequest,
    ReflectionResponse,
    CapabilityMapResponse,
    AuthRegisterRequest,
    AuthLoginRequest,
    AuthUserResponse,
    AuthTokenResponse,
    ClarificationTaskResponse,
    ClarificationTaskListResponse,
    ClarificationResolveRequest,
    MemorySettingsResponse,
    JournalEntryCreateRequest,
    JournalEntryResponse,
    ProjectionJobResponse,
    JournalIngestResponse,
    JournalEntryListResponse,
    ProjectionJobListResponse,
    ProjectionRunResponse,
    DerivedStoreCleanupResponse,
    JournalDeleteResponse,
    LocalDataWipeResponse,
    UserDataDeleteResponse,
    WeaviateArtifactResponse,
    GraphNodeResponse,
    GraphRelationshipResponse,
    GraphObservationResponse,
    MemoryDebugResponse,
    ReviewFindingResponse,
    ReviewStatResponse,
    WeeklyReviewResponse,
]

__all__ = [
    "AuthLoginRequest",
    "AuthRegisterRequest",
    "AuthTokenResponse",
    "AuthUserResponse",
    "CapabilityMapResponse",
    "ClarificationResolveRequest",
    "ClarificationTaskListResponse",
    "ClarificationTaskResponse",
    "DerivedStoreCleanupResponse",
    "JournalDeleteResponse",
    "LocalDataWipeResponse",
    "UserDataDeleteResponse",
    "JournalEntryCreateRequest",
    "JournalEntryListResponse",
    "JournalEntryResponse",
    "JournalIngestResponse",
    "MemorySettingsResponse",
    "MemoryDebugResponse",
    "GraphNodeResponse",
    "GraphObservationResponse",
    "GraphRelationshipResponse",
    "ProjectionJobListResponse",
    "ProjectionJobResponse",
    "ProjectionRunResponse",
    "ReviewFindingResponse",
    "ReviewStatResponse",
    "WeeklyReviewResponse",
    "WeaviateArtifactResponse",
    "ReflectionRequest",
    "ReflectionResponse",
    "SCHEMA_MODELS",
]
