from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel


BACKEND_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_DIR.parents[1]

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.schemas import SCHEMA_MODELS  # noqa: E402


def render_literal(value: Any) -> str:
    return json.dumps(value)


def unique(items: list[str]) -> list[str]:
    seen: dict[str, None] = {}
    for item in items:
        seen.setdefault(item, None)
    return list(seen.keys())


def render_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]

    if "enum" in schema:
        return " | ".join(render_literal(value) for value in schema["enum"])

    union_schema = schema.get("anyOf") or schema.get("oneOf")
    if union_schema:
        return " | ".join(unique([render_type(option) for option in union_schema]))

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(unique([render_type({"type": value}) for value in schema_type]))

    if schema_type == "array":
        item_type = render_type(schema.get("items", {}))
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"

    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if properties:
            lines = ["{"]
            for name, property_schema in properties.items():
                marker = "" if name in required else "?"
                lines.append(f"  {name}{marker}: {render_type(property_schema)};")
            lines.append("}")
            return "\n".join(lines)

        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {render_type(additional)}>"
        return "Record<string, unknown>"

    primitive_map = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    return primitive_map.get(schema_type, "unknown")


def render_definition(name: str, schema: dict[str, Any], export: bool = False) -> str:
    prefix = "export " if export else ""
    if schema.get("type") == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = [f"{prefix}interface {name} {{"]
        for property_name, property_schema in properties.items():
            marker = "" if property_name in required else "?"
            lines.append(f"  {property_name}{marker}: {render_type(property_schema)};")
        lines.append("}")
        return "\n".join(lines)

    return f"{prefix}type {name} = {render_type(schema)};"


def collect_model_schemas(
    models: list[type[BaseModel]],
) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
    model_schemas: dict[str, dict[str, Any]] = {}
    definitions: dict[str, dict[str, Any]] = {}

    for model in models:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        model_schemas[model.__name__] = schema
        definitions.update(schema.get("$defs", {}))

    return model_schemas, definitions


def render_file(models: list[type[BaseModel]]) -> str:
    model_schemas, definitions = collect_model_schemas(models)
    sections = [
        "// This file is generated by apps/backend/scripts/generate_types.py",
        "// Do not edit it by hand.",
        "",
    ]

    for name in sorted(definitions):
        sections.append(render_definition(name, definitions[name]))
        sections.append("")

    for name in sorted(model_schemas):
        sections.append(render_definition(name, model_schemas[name], export=True))
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    output_dir = REPO_ROOT / "packages" / "types" / "src" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "reflection.ts"
    output_file.write_text(render_file(SCHEMA_MODELS), encoding="utf-8")

    index_file = output_dir / "index.ts"
    index_file.write_text('export * from "./reflection";\n', encoding="utf-8")


if __name__ == "__main__":
    main()
