name: Midas
options:
  minimumXcodeGenVersion: 2.42.0
targets:
  Midas:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Midas
        excludes:
          - Appicon.png
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clarkmyfancy.midas
        SWIFT_VERSION: "5.10"
        PRODUCT_NAME: Midas
        INFOPLIST_FILE: Midas/Info.plist
        CODE_SIGN_ENTITLEMENTS: Midas/Midas.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
